### ISSUE TITLE
Eliminar clases Consolidado y Programa Académico

### ISSUE THREAD

**Issue by juanpnaranjo2006** [300CIS017-Object-Oriented-Programming/proyecto-3-syntax_pro_trump#23]
Para optimizar el prgorama, debido a la inmensa cantidad de datos, se eliminarán las clases consolidado y programa académico como estructuras para guardar datos y, en su lugar utilizaremos directamente los dataframes de la libreria pandas.

**Comment by zulu27** [comment]
Hecho

**Comment by zulu27** [comment]
hecho
