### ISSUE TITLE
Unificar Diccionarios de atributos - consolidado

### ISSUE THREAD

**Issue by juanpnaranjo2006** [300CIS017-Object-Oriented-Programming/proyecto-3-syntax_pro_trump#3]
Python, a diferencia de C++, permite contenedores con datos de distinto tipo. Aprovechando esto, hacer que los diccionarios de atributos de la clase consolidado sean uno solo

**Comment by zulu27** [comment]
ya se creo la clase con la implementación de los diccionarios en la clase consolidado consultar rama Consolidado
